/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, OrthographicCamera, useAnimations } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    mesh_1: THREE.Mesh;
    mesh_2: THREE.Mesh;
    mesh_3: THREE.Mesh;
    mesh_4: THREE.Mesh;
    mesh_5: THREE.Mesh;
    mesh_6: THREE.Mesh;
    mesh_7: THREE.Mesh;
    mesh_8: THREE.Mesh;
    mesh_9: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_11: THREE.Mesh;
    mesh_12: THREE.Mesh;
    mesh_13: THREE.Mesh;
    mesh_14: THREE.Mesh;
    mesh_15: THREE.Mesh;
    mesh_16: THREE.Mesh;
    mesh_17: THREE.Mesh;
    mesh_18: THREE.Mesh;
    mesh_19: THREE.Mesh;
    mesh_20: THREE.Mesh;
    mesh_21: THREE.Mesh;
    mesh_22: THREE.Mesh;
    mesh_23: THREE.Mesh;
    mesh_24: THREE.Mesh;
    mesh_25: THREE.Mesh;
    mesh_26: THREE.Mesh;
    mesh_27: THREE.Mesh;
    mesh_28: THREE.Mesh;
    mesh_29: THREE.Mesh;
    mesh_30: THREE.Mesh;
    mesh_31: THREE.Mesh;
    mesh_32: THREE.Mesh;
    mesh_33: THREE.Mesh;
    mesh_34: THREE.Mesh;
    mesh_35: THREE.Mesh;
    mesh_36: THREE.Mesh;
    mesh_37: THREE.Mesh;
    mesh_38: THREE.Mesh;
    mesh_39: THREE.Mesh;
    mesh_40: THREE.Mesh;
    mesh_41: THREE.Mesh;
    mesh_42: THREE.Mesh;
    mesh_43: THREE.Mesh;
    mesh_44: THREE.Mesh;
    mesh_45: THREE.Mesh;
    mesh_46: THREE.Mesh;
    mesh_47: THREE.Mesh;
    mesh_48: THREE.Mesh;
    mesh_49: THREE.Mesh;
    mesh_50: THREE.Mesh;
    mesh_51: THREE.Mesh;
    mesh_52: THREE.Mesh;
    mesh_53: THREE.Mesh;
    mesh_54: THREE.Mesh;
    mesh_55: THREE.Mesh;
    mesh_56: THREE.Mesh;
    mesh_57: THREE.Mesh;
    mesh_58: THREE.Mesh;
    mesh_59: THREE.Mesh;
    mesh_60: THREE.Mesh;
    mesh_61: THREE.Mesh;
    mesh_62: THREE.Mesh;
    mesh_63: THREE.Mesh;
    mesh_64: THREE.Mesh;
    mesh_65: THREE.Mesh;
    mesh_66: THREE.Mesh;
    mesh_67: THREE.Mesh;
    mesh_68: THREE.Mesh;
    mesh_69: THREE.Mesh;
    mesh_70: THREE.Mesh;
    mesh_71: THREE.Mesh;
    mesh_72: THREE.Mesh;
    mesh_73: THREE.Mesh;
    mesh_74: THREE.Mesh;
    mesh_75: THREE.Mesh;
    mesh_76: THREE.Mesh;
    mesh_77: THREE.Mesh;
    mesh_78: THREE.Mesh;
    mesh_79: THREE.Mesh;
    mesh_80: THREE.Mesh;
    mesh_81: THREE.Mesh;
    mesh_82: THREE.Mesh;
    mesh_83: THREE.Mesh;
    mesh_84: THREE.Mesh;
    mesh_85: THREE.Mesh;
    mesh_86: THREE.Mesh;
    mesh_87: THREE.Mesh;
    mesh_88: THREE.Mesh;
    mesh_89: THREE.Mesh;
    mesh_90: THREE.Mesh;
    mesh_91: THREE.Mesh;
    mesh_92: THREE.Mesh;
    mesh_93: THREE.Mesh;
    mesh_94: THREE.Mesh;
    mesh_95: THREE.Mesh;
    mesh_96: THREE.Mesh;
    mesh_97: THREE.Mesh;
    mesh_98: THREE.Mesh;
    mesh_99: THREE.Mesh;
    mesh_100: THREE.Mesh;
    mesh_101: THREE.Mesh;
    mesh_102: THREE.Mesh;
    mesh_103: THREE.Mesh;
    mesh_104: THREE.Mesh;
    mesh_105: THREE.Mesh;
    mesh_106: THREE.Mesh;
    mesh_107: THREE.Mesh;
    mesh_108: THREE.Mesh;
    mesh_109: THREE.Mesh;
    mesh_110: THREE.Mesh;
    mesh_111: THREE.Mesh;
    mesh_112: THREE.Mesh;
    mesh_113: THREE.Mesh;
    mesh_114: THREE.Mesh;
    mesh_115: THREE.Mesh;
    mesh_116: THREE.Mesh;
    mesh_117: THREE.Mesh;
    mesh_118: THREE.Mesh;
    mesh_119: THREE.Mesh;
    mesh_120: THREE.Mesh;
    mesh_121: THREE.Mesh;
    mesh_122: THREE.Mesh;
    mesh_123: THREE.Mesh;
    mesh_124: THREE.Mesh;
    mesh_125: THREE.Mesh;
    mesh_126: THREE.Mesh;
    mesh_127: THREE.Mesh;
    mesh_128: THREE.Mesh;
    mesh_129: THREE.Mesh;
    mesh_130: THREE.Mesh;
    mesh_131: THREE.Mesh;
    mesh_132: THREE.Mesh;
    mesh_133: THREE.Mesh;
    mesh_134: THREE.Mesh;
    mesh_135: THREE.Mesh;
    mesh_136: THREE.Mesh;
    mesh_137: THREE.Mesh;
    mesh_138: THREE.Mesh;
    mesh_139: THREE.Mesh;
    mesh_140: THREE.Mesh;
    mesh_141: THREE.Mesh;
    mesh_142: THREE.Mesh;
    mesh_143: THREE.Mesh;
    mesh_144: THREE.Mesh;
    mesh_145: THREE.Mesh;
    mesh_146: THREE.Mesh;
    mesh_147: THREE.Mesh;
    mesh_148: THREE.Mesh;
    mesh_149: THREE.Mesh;
    mesh_150: THREE.Mesh;
    mesh_151: THREE.Mesh;
    mesh_152: THREE.Mesh;
    mesh_153: THREE.Mesh;
    mesh_154: THREE.Mesh;
    mesh_155: THREE.Mesh;
    mesh_156: THREE.Mesh;
    mesh_157: THREE.Mesh;
    mesh_158: THREE.Mesh;
    mesh_159: THREE.Mesh;
    mesh_160: THREE.Mesh;
    mesh_161: THREE.Mesh;
    mesh_162: THREE.Mesh;
    mesh_163: THREE.Mesh;
    mesh_164: THREE.Mesh;
    mesh_165: THREE.Mesh;
    mesh_166: THREE.Mesh;
    mesh_167: THREE.Mesh;
    mesh_168: THREE.Mesh;
    mesh_169: THREE.Mesh;
    mesh_170: THREE.Mesh;
    mesh_171: THREE.Mesh;
    mesh_172: THREE.Mesh;
    mesh_173: THREE.Mesh;
    mesh_174: THREE.Mesh;
    mesh_175: THREE.Mesh;
    mesh_176: THREE.Mesh;
    mesh_177: THREE.Mesh;
    mesh_178: THREE.Mesh;
    mesh_179: THREE.Mesh;
    mesh_180: THREE.Mesh;
    mesh_181: THREE.Mesh;
    mesh_182: THREE.Mesh;
    mesh_183: THREE.Mesh;
    mesh_184: THREE.Mesh;
    mesh_185: THREE.Mesh;
    mesh_186: THREE.Mesh;
    mesh_187: THREE.Mesh;
    mesh_188: THREE.Mesh;
    mesh_189: THREE.Mesh;
    mesh_190: THREE.Mesh;
    mesh_191: THREE.Mesh;
    mesh_192: THREE.Mesh;
    mesh_193: THREE.Mesh;
    mesh_194: THREE.Mesh;
    mesh_195: THREE.Mesh;
    mesh_196: THREE.Mesh;
    mesh_197: THREE.Mesh;
    mesh_198: THREE.Mesh;
    mesh_199: THREE.Mesh;
    mesh_200: THREE.Mesh;
    mesh_201: THREE.Mesh;
    mesh_202: THREE.Mesh;
    mesh_203: THREE.Mesh;
    mesh_204: THREE.Mesh;
    mesh_205: THREE.Mesh;
    mesh_206: THREE.Mesh;
    mesh_207: THREE.Mesh;
    mesh_208: THREE.Mesh;
    mesh_209: THREE.Mesh;
    mesh_210: THREE.Mesh;
    mesh_211: THREE.Mesh;
    mesh_212: THREE.Mesh;
    mesh_213: THREE.Mesh;
    mesh_214: THREE.Mesh;
    mesh_215: THREE.Mesh;
    mesh_216: THREE.Mesh;
    mesh_217: THREE.Mesh;
    mesh_218: THREE.Mesh;
    mesh_219: THREE.Mesh;
    mesh_220: THREE.Mesh;
    mesh_221: THREE.Mesh;
    mesh_222: THREE.Mesh;
    mesh_223: THREE.Mesh;
    mesh_224: THREE.Mesh;
    mesh_225: THREE.Mesh;
    mesh_226: THREE.Mesh;
    mesh_227: THREE.Mesh;
    mesh_228: THREE.Mesh;
    mesh_229: THREE.Mesh;
    mesh_230: THREE.Mesh;
    mesh_231: THREE.Mesh;
    mesh_232: THREE.Mesh;
    mesh_233: THREE.Mesh;
    mesh_234: THREE.Mesh;
    mesh_235: THREE.Mesh;
    mesh_236: THREE.Mesh;
    mesh_237: THREE.Mesh;
    mesh_238: THREE.Mesh;
    mesh_239: THREE.Mesh;
    mesh_240: THREE.Mesh;
    mesh_241: THREE.Mesh;
    mesh_242: THREE.Mesh;
    mesh_243: THREE.Mesh;
    mesh_244: THREE.Mesh;
    mesh_245: THREE.Mesh;
    mesh_246: THREE.Mesh;
    mesh_247: THREE.Mesh;
    mesh_248: THREE.Mesh;
    mesh_249: THREE.Mesh;
    mesh_250: THREE.Mesh;
    mesh_251: THREE.Mesh;
    mesh_252: THREE.Mesh;
    mesh_253: THREE.Mesh;
    mesh_254: THREE.Mesh;
    mesh_255: THREE.Mesh;
    mesh_256: THREE.Mesh;
    mesh_257: THREE.Mesh;
    mesh_258: THREE.Mesh;
    mesh_259: THREE.Mesh;
    mesh_260: THREE.Mesh;
    mesh_261: THREE.Mesh;
    mesh_262: THREE.Mesh;
    mesh_263: THREE.Mesh;
    mesh_264: THREE.Mesh;
    mesh_265: THREE.Mesh;
    mesh_266: THREE.Mesh;
    mesh_267: THREE.Mesh;
    mesh_268: THREE.Mesh;
    mesh_269: THREE.Mesh;
    mesh_270: THREE.Mesh;
    mesh_271: THREE.Mesh;
    mesh_272: THREE.Mesh;
    mesh_273: THREE.Mesh;
    mesh_274: THREE.Mesh;
    mesh_275: THREE.Mesh;
    mesh_276: THREE.Mesh;
    mesh_277: THREE.Mesh;
    mesh_278: THREE.Mesh;
    mesh_279: THREE.Mesh;
    mesh_280: THREE.Mesh;
    mesh_281: THREE.Mesh;
    mesh_282: THREE.Mesh;
    mesh_283: THREE.Mesh;
    mesh_284: THREE.Mesh;
    mesh_285: THREE.Mesh;
    mesh_286: THREE.Mesh;
    mesh_287: THREE.Mesh;
    mesh_288: THREE.Mesh;
    mesh_289: THREE.Mesh;
    mesh_290: THREE.Mesh;
    mesh_291: THREE.Mesh;
    mesh_0: THREE.Mesh;
    mesh_292: THREE.Mesh;
  };
  materials: {};
};

type ActionName = 'animation_0';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    '/lego_world-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[7.96, 0, 0]} />
      <group position={[0, 0, 8]} />
      <group position={[7.96, 0, 8]} />
      <group position={[-15.91, 0, 0]} />
      <group position={[0, 0, 15.96]} />
      <group position={[-15.91, 0, 15.96]} />
      <group position={[-31.79, 0, 0]} />
      <group position={[-31.79, 0, 31.91]} />
      <group position={[0, 0, 31.91]} />
      <group position={[0, 0.3, 0]} />
      <group position={[0, 0, 1.3]} scale={[0.13, 1.52, 1.34]} />
      <group position={[0, 0, -1.24]} scale={[0.13, 1.52, 1.34]} />
      <group position={[-0.03, 1.82, 57.84]} />
      <group position={[7.95, 1.82, 57.84]} />
      <group position={[-0.03, 3.81, 57.84]} />
      <group position={[7.95, 3.81, 57.84]} />
      <group position={[-0.03, 5.79, 57.84]} />
      <group position={[7.95, 5.79, 57.84]} />
      <group position={[7.95, 7.79, 57.84]} />
      <group position={[-0.03, 7.79, 57.84]} />
      <group position={[-0.03, 9.66, 57.84]} />
      <group position={[7.95, 9.66, 57.84]} />
      <group position={[7.95, 11.65, 57.84]} />
      <group position={[-0.03, 11.65, 57.84]} />
      <group position={[7.95, 13.63, 57.84]} />
      <group position={[-0.03, 15.62, 57.84]} />
      <group position={[7.95, 15.62, 57.84]} />
      <group position={[-0.03, 13.63, 57.84]} />
      <group position={[-0.03, 17.46, 57.84]} />
      <group position={[7.95, 17.46, 57.84]} />
      <group position={[7.95, 19.45, 57.84]} />
      <group position={[-0.03, 19.45, 57.84]} />
      <group position={[7.95, 21.43, 57.84]} />
      <group position={[-0.03, 23.43, 57.84]} />
      <group position={[7.95, 23.43, 57.84]} />
      <group position={[-0.03, 21.43, 57.84]} />
      <group position={[-0.03, 27.29, 57.84]} />
      <group position={[7.95, 27.29, 57.84]} />
      <group position={[-0.03, 25.3, 57.84]} />
      <group position={[7.95, 25.3, 57.84]} />
      <group position={[-15.93, 1.82, 57.84]} />
      <group position={[-15.93, 13.63, 57.84]} />
      <group position={[-7.95, 15.62, 57.84]} />
      <group position={[-15.93, 15.62, 57.84]} />
      <group position={[-7.95, 13.63, 57.84]} />
      <group position={[-7.95, 25.3, 57.84]} />
      <group position={[-15.93, 25.3, 57.84]} />
      <group position={[-7.95, 27.29, 57.84]} />
      <group position={[-7.95, 1.82, 57.84]} />
      <group position={[-7.95, 3.81, 57.84]} />
      <group position={[-15.93, 3.81, 57.84]} />
      <group position={[-7.95, 5.79, 57.84]} />
      <group position={[-15.93, 7.79, 57.84]} />
      <group position={[-7.95, 7.79, 57.84]} />
      <group position={[-15.93, 17.46, 57.84]} />
      <group position={[-15.93, 27.29, 57.84]} />
      <group position={[-15.93, 21.43, 57.84]} />
      <group position={[-7.95, 23.43, 57.84]} />
      <group position={[-15.93, 23.43, 57.84]} />
      <group position={[-7.95, 21.43, 57.84]} />
      <group position={[-15.93, 19.45, 57.84]} />
      <group position={[-7.95, 19.45, 57.84]} />
      <group position={[-7.95, 17.46, 57.84]} />
      <group position={[-15.93, 5.79, 57.84]} />
      <group position={[-15.93, 11.65, 57.84]} />
      <group position={[-7.95, 11.65, 57.84]} />
      <group position={[-15.93, 9.66, 57.84]} />
      <group position={[-7.95, 9.66, 57.84]} />
      <group position={[-31.84, 1.82, 57.84]} />
      <group position={[-31.84, 13.63, 57.84]} />
      <group position={[-23.86, 15.62, 57.84]} />
      <group position={[-31.84, 15.62, 57.84]} />
      <group position={[-23.86, 13.63, 57.84]} />
      <group position={[-23.86, 25.3, 57.84]} />
      <group position={[-31.84, 25.3, 57.84]} />
      <group position={[-23.86, 27.29, 57.84]} />
      <group position={[-23.86, 1.82, 57.84]} />
      <group position={[-23.86, 3.81, 57.84]} />
      <group position={[-31.84, 3.81, 57.84]} />
      <group position={[-23.86, 5.79, 57.84]} />
      <group position={[-31.84, 7.79, 57.84]} />
      <group position={[-23.86, 7.79, 57.84]} />
      <group position={[-31.84, 17.46, 57.84]} />
      <group position={[-39.77, 5.79, 57.84]} />
      <group position={[-47.75, 3.81, 57.84]} />
      <group position={[-39.77, 3.81, 57.84]} />
      <group position={[-39.77, 1.82, 57.84]} />
      <group position={[-39.77, 27.29, 57.84]} />
      <group position={[-47.75, 25.3, 57.84]} />
      <group position={[-39.77, 25.3, 57.84]} />
      <group position={[-39.77, 13.63, 57.84]} />
      <group position={[-47.75, 15.62, 57.84]} />
      <group position={[-39.77, 15.62, 57.84]} />
      <group position={[-47.75, 13.63, 57.84]} />
      <group position={[-47.75, 1.82, 57.84]} />
      <group position={[-39.77, 17.46, 57.84]} />
      <group position={[-39.77, 19.45, 57.84]} />
      <group position={[-47.75, 19.45, 57.84]} />
      <group position={[-39.77, 21.43, 57.84]} />
      <group position={[-47.75, 23.43, 57.84]} />
      <group position={[-39.77, 23.43, 57.84]} />
      <group position={[-47.75, 21.43, 57.84]} />
      <group position={[-47.75, 27.29, 57.84]} />
      <group position={[-47.75, 17.46, 57.84]} />
      <group position={[-39.77, 7.79, 57.84]} />
      <group position={[-47.75, 7.79, 57.84]} />
      <group position={[-31.84, 27.29, 57.84]} />
      <group position={[-31.84, 21.43, 57.84]} />
      <group position={[-23.86, 23.43, 57.84]} />
      <group position={[-31.84, 23.43, 57.84]} />
      <group position={[-23.86, 21.43, 57.84]} />
      <group position={[-31.84, 19.45, 57.84]} />
      <group position={[-23.86, 19.45, 57.84]} />
      <group position={[-23.86, 17.46, 57.84]} />
      <group position={[-31.84, 5.79, 57.84]} />
      <group position={[-31.84, 11.65, 57.84]} />
      <group position={[-23.86, 11.65, 57.84]} />
      <group position={[-31.84, 9.66, 57.84]} />
      <group position={[-23.86, 9.66, 57.84]} />
      <group position={[-39.77, 9.66, 57.84]} />
      <group position={[-47.75, 9.66, 57.84]} />
      <group position={[-39.77, 11.65, 57.84]} />
      <group position={[-47.75, 11.65, 57.84]} />
      <group position={[-47.75, 5.79, 57.84]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group position={[24.95, 11.43, 41.96]} />
      <group
        position={[-34.87, -8.86, -14.79]}
        rotation={[0, 0.02, 0]}
        scale={0.32}
      />
      <group position={[0, 0, 1.3]} scale={[0.13, 1.52, 1.34]} />
      <group position={[0, 0, -1.24]} scale={[0.13, 1.52, 1.34]} />
      <group position={[-41.86, 1.83, 37.8]} />
      <group position={[-5.19, 1.9, 41.21]} />
      <group position={[-41.86, 3.84, 37.8]} />
      <group position={[-33.92, 3.84, 37.8]} />
      <group position={[-41.86, 3.83, 33.82]} />
      <group position={[-5.19, 3.84, 37.23]} />
      <group position={[-41.86, 1.83, 33.82]} />
      <group position={[-5.19, 1.84, 37.23]} />
      <group position={[-33.92, 7.83, 33.82]} />
      <group position={[-33.92, 5.83, 33.82]} />
      <group position={[-33.92, 7.83, 37.8]} />
      <group position={[-33.92, 5.83, 37.8]} />
      <group position={[-33.92, 11.76, 33.82]} />
      <group position={[-33.92, 9.76, 33.82]} />
      <group position={[-33.92, 13.74, 37.8]} />
      <group position={[-33.92, 11.76, 37.8]} />
      <group position={[-33.92, 13.74, 33.82]} />
      <group position={[-33.92, 15.74, 37.8]} />
      <group position={[-33.92, 15.74, 33.82]} />
      <group position={[-33.92, 9.76, 37.8]} />
      <group position={[8.06, 13.7, 17.97]} />
      <group position={[8.06, 9.71, 17.97]} />
      <group position={[8.06, 9.71, 21.95]} />
      <group position={[8.06, 11.71, 21.95]} />
      <group position={[8.06, 15.7, 17.97]} />
      <group position={[8.06, 13.7, 21.95]} />
      <group position={[8.06, 15.7, 21.95]} />
      <group position={[8.06, 3.8, 17.97]} />
      <group position={[8.06, 1.8, 17.97]} />
      <group position={[8.06, 5.78, 21.95]} />
      <group position={[8.06, 3.8, 21.95]} />
      <group position={[8.06, 5.78, 17.97]} />
      <group position={[8.06, 7.78, 21.95]} />
      <group position={[8.06, 7.78, 17.97]} />
      <group position={[8.06, 1.8, 21.95]} />
      <group position={[8.06, 11.71, 17.97]} />
      <group position={[0.13, 3.8, 21.94]} />
      <group position={[0.13, 3.8, 17.96]} />
      <group position={[0.13, 1.8, 17.96]} />
      <group position={[0.13, 1.8, 21.94]} />
      <group position={[-41.86, 7.85, 37.8]} />
      <group position={[-41.86, 7.85, 33.82]} />
      <group position={[-41.86, 5.86, 33.82]} />
      <group position={[-41.86, 5.86, 37.8]} />
      <group position={[0.13, 7.81, 17.96]} />
      <group position={[0.13, 5.81, 17.96]} />
      <group position={[0.13, 5.81, 21.94]} />
      <group position={[0.13, 7.81, 21.94]} />
      <group position={[26.21, 10.47, 9.88]} />
      <group position={[26.2, 12.47, 9.88]} />
      <group position={[26.21, 14.46, 9.88]} />
      <group position={[26.2, 16.45, 9.88]} />
      <group position={[18.27, 4.56, 9.88]} />
      <group position={[26.21, 6.54, 9.88]} />
      <group position={[26.2, 4.56, 9.88]} />
      <group position={[18.27, 8.57, 9.88]} />
      <group position={[18.27, 6.57, 9.88]} />
      <group position={[18.27, 2.56, 9.88]} />
      <group position={[26.2, 8.54, 9.88]} />
      <group position={[26.21, 2.56, 9.88]} />
      <group position={[-42.2, -0.73, 5.73]} rotation={[-0.08, 1.56, 0.08]} />
      <group position={[-12.36, -0.83, 37.78]} rotation={[-0.08, 1.56, 0.08]} />
      <group position={[0, 0, 1.3]} scale={[0.13, 1.52, 1.34]} />
      <group position={[0, 0, -1.24]} scale={[0.13, 1.52, 1.34]} />
      <group position={[-33.26, 1.8, 7.73]} />
      <group position={[-33.26, 3.77, 7.73]} />
      <group position={[-41.25, 1.8, 7.73]} />
      <group position={[-41.25, 3.77, 7.73]} />
      <group position={[-33.28, 3.81, 3.75]} />
      <group position={[-33.28, 1.84, 3.75]} />
      <group position={[-33.24, 7.77, 3.75]} />
      <group position={[-33.24, 5.8, 3.75]} />
      <group position={[-33.26, 5.78, 7.72]} />
      <group position={[-42.2, -0.73, 40.4]} rotation={[3.14, 0, 3.14]} />
      <group position={[-15.99, 9.85, 50.3]} />
      <group position={[-15.99, 11.85, 50.3]} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
      <mesh
        geometry={nodes.mesh_10.geometry}
        material={nodes.mesh_10.material}
      />
      <mesh
        geometry={nodes.mesh_11.geometry}
        material={nodes.mesh_11.material}
      />
      <mesh
        geometry={nodes.mesh_12.geometry}
        material={nodes.mesh_12.material}
      />
      <mesh
        geometry={nodes.mesh_13.geometry}
        material={nodes.mesh_13.material}
      />
      <mesh
        geometry={nodes.mesh_14.geometry}
        material={nodes.mesh_14.material}
      />
      <mesh
        geometry={nodes.mesh_15.geometry}
        material={nodes.mesh_15.material}
      />
      <mesh
        geometry={nodes.mesh_16.geometry}
        material={nodes.mesh_16.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_17.geometry}
        material={nodes.mesh_17.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_18.geometry}
        material={nodes.mesh_18.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_19.geometry}
        material={nodes.mesh_19.material}
      />
      <mesh
        geometry={nodes.mesh_20.geometry}
        material={nodes.mesh_20.material}
      />
      <mesh
        geometry={nodes.mesh_21.geometry}
        material={nodes.mesh_21.material}
      />
      <mesh
        geometry={nodes.mesh_22.geometry}
        material={nodes.mesh_22.material}
      />
      <mesh
        geometry={nodes.mesh_23.geometry}
        material={nodes.mesh_23.material}
      />
      <mesh
        geometry={nodes.mesh_24.geometry}
        material={nodes.mesh_24.material}
      />
      <mesh
        geometry={nodes.mesh_25.geometry}
        material={nodes.mesh_25.material}
      />
      <mesh
        geometry={nodes.mesh_26.geometry}
        material={nodes.mesh_26.material}
      />
      <mesh
        geometry={nodes.mesh_27.geometry}
        material={nodes.mesh_27.material}
      />
      <mesh
        geometry={nodes.mesh_28.geometry}
        material={nodes.mesh_28.material}
      />
      <mesh
        geometry={nodes.mesh_29.geometry}
        material={nodes.mesh_29.material}
      />
      <mesh
        geometry={nodes.mesh_30.geometry}
        material={nodes.mesh_30.material}
      />
      <mesh
        geometry={nodes.mesh_31.geometry}
        material={nodes.mesh_31.material}
      />
      <mesh
        geometry={nodes.mesh_32.geometry}
        material={nodes.mesh_32.material}
      />
      <mesh
        geometry={nodes.mesh_33.geometry}
        material={nodes.mesh_33.material}
      />
      <mesh
        geometry={nodes.mesh_34.geometry}
        material={nodes.mesh_34.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_35.geometry}
        material={nodes.mesh_35.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_36.geometry}
        material={nodes.mesh_36.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_37.geometry}
        material={nodes.mesh_37.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_38.geometry}
        material={nodes.mesh_38.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_39.geometry}
        material={nodes.mesh_39.material}
        position={[1.28, 0, -1.03]}
      />
      <mesh
        geometry={nodes.mesh_40.geometry}
        material={nodes.mesh_40.material}
      />
      <mesh
        geometry={nodes.mesh_41.geometry}
        material={nodes.mesh_41.material}
      />
      <mesh
        geometry={nodes.mesh_42.geometry}
        material={nodes.mesh_42.material}
      />
      <mesh
        geometry={nodes.mesh_43.geometry}
        material={nodes.mesh_43.material}
      />
      <mesh
        geometry={nodes.mesh_44.geometry}
        material={nodes.mesh_44.material}
      />
      <mesh
        geometry={nodes.mesh_45.geometry}
        material={nodes.mesh_45.material}
      />
      <mesh
        geometry={nodes.mesh_46.geometry}
        material={nodes.mesh_46.material}
      />
      <mesh
        geometry={nodes.mesh_47.geometry}
        material={nodes.mesh_47.material}
      />
      <mesh
        geometry={nodes.mesh_48.geometry}
        material={nodes.mesh_48.material}
      />
      <mesh
        geometry={nodes.mesh_49.geometry}
        material={nodes.mesh_49.material}
      />
      <mesh
        geometry={nodes.mesh_50.geometry}
        material={nodes.mesh_50.material}
      />
      <mesh
        geometry={nodes.mesh_51.geometry}
        material={nodes.mesh_51.material}
      />
      <mesh
        geometry={nodes.mesh_52.geometry}
        material={nodes.mesh_52.material}
      />
      <mesh
        geometry={nodes.mesh_53.geometry}
        material={nodes.mesh_53.material}
      />
      <mesh
        geometry={nodes.mesh_54.geometry}
        material={nodes.mesh_54.material}
      />
      <mesh
        geometry={nodes.mesh_55.geometry}
        material={nodes.mesh_55.material}
      />
      <mesh
        geometry={nodes.mesh_56.geometry}
        material={nodes.mesh_56.material}
      />
      <mesh
        geometry={nodes.mesh_57.geometry}
        material={nodes.mesh_57.material}
      />
      <mesh
        geometry={nodes.mesh_58.geometry}
        material={nodes.mesh_58.material}
      />
      <mesh
        geometry={nodes.mesh_59.geometry}
        material={nodes.mesh_59.material}
      />
      <mesh
        geometry={nodes.mesh_60.geometry}
        material={nodes.mesh_60.material}
      />
      <mesh
        geometry={nodes.mesh_61.geometry}
        material={nodes.mesh_61.material}
      />
      <mesh
        geometry={nodes.mesh_62.geometry}
        material={nodes.mesh_62.material}
      />
      <mesh
        geometry={nodes.mesh_63.geometry}
        material={nodes.mesh_63.material}
      />
      <mesh
        geometry={nodes.mesh_64.geometry}
        material={nodes.mesh_64.material}
      />
      <mesh
        geometry={nodes.mesh_65.geometry}
        material={nodes.mesh_65.material}
      />
      <mesh
        geometry={nodes.mesh_66.geometry}
        material={nodes.mesh_66.material}
      />
      <mesh
        geometry={nodes.mesh_67.geometry}
        material={nodes.mesh_67.material}
      />
      <mesh
        geometry={nodes.mesh_68.geometry}
        material={nodes.mesh_68.material}
      />
      <mesh
        geometry={nodes.mesh_69.geometry}
        material={nodes.mesh_69.material}
      />
      <mesh
        geometry={nodes.mesh_70.geometry}
        material={nodes.mesh_70.material}
      />
      <mesh
        geometry={nodes.mesh_71.geometry}
        material={nodes.mesh_71.material}
      />
      <mesh
        geometry={nodes.mesh_72.geometry}
        material={nodes.mesh_72.material}
      />
      <mesh
        geometry={nodes.mesh_73.geometry}
        material={nodes.mesh_73.material}
      />
      <mesh
        geometry={nodes.mesh_74.geometry}
        material={nodes.mesh_74.material}
      />
      <mesh
        geometry={nodes.mesh_75.geometry}
        material={nodes.mesh_75.material}
      />
      <mesh
        geometry={nodes.mesh_76.geometry}
        material={nodes.mesh_76.material}
      />
      <mesh
        geometry={nodes.mesh_77.geometry}
        material={nodes.mesh_77.material}
      />
      <mesh
        geometry={nodes.mesh_78.geometry}
        material={nodes.mesh_78.material}
      />
      <mesh
        geometry={nodes.mesh_79.geometry}
        material={nodes.mesh_79.material}
      />
      <mesh
        geometry={nodes.mesh_80.geometry}
        material={nodes.mesh_80.material}
      />
      <mesh
        geometry={nodes.mesh_81.geometry}
        material={nodes.mesh_81.material}
      />
      <mesh
        geometry={nodes.mesh_82.geometry}
        material={nodes.mesh_82.material}
      />
      <mesh
        geometry={nodes.mesh_83.geometry}
        material={nodes.mesh_83.material}
      />
      <mesh
        geometry={nodes.mesh_84.geometry}
        material={nodes.mesh_84.material}
      />
      <mesh
        geometry={nodes.mesh_85.geometry}
        material={nodes.mesh_85.material}
      />
      <mesh
        geometry={nodes.mesh_86.geometry}
        material={nodes.mesh_86.material}
      />
      <mesh
        geometry={nodes.mesh_87.geometry}
        material={nodes.mesh_87.material}
      />
      <mesh
        geometry={nodes.mesh_88.geometry}
        material={nodes.mesh_88.material}
      />
      <mesh
        geometry={nodes.mesh_89.geometry}
        material={nodes.mesh_89.material}
      />
      <mesh
        geometry={nodes.mesh_90.geometry}
        material={nodes.mesh_90.material}
      />
      <mesh
        geometry={nodes.mesh_91.geometry}
        material={nodes.mesh_91.material}
      />
      <mesh
        geometry={nodes.mesh_92.geometry}
        material={nodes.mesh_92.material}
      />
      <mesh
        geometry={nodes.mesh_93.geometry}
        material={nodes.mesh_93.material}
      />
      <mesh
        geometry={nodes.mesh_94.geometry}
        material={nodes.mesh_94.material}
      />
      <mesh
        geometry={nodes.mesh_95.geometry}
        material={nodes.mesh_95.material}
      />
      <mesh
        geometry={nodes.mesh_96.geometry}
        material={nodes.mesh_96.material}
      />
      <mesh
        geometry={nodes.mesh_97.geometry}
        material={nodes.mesh_97.material}
      />
      <mesh
        geometry={nodes.mesh_98.geometry}
        material={nodes.mesh_98.material}
      />
      <mesh
        geometry={nodes.mesh_99.geometry}
        material={nodes.mesh_99.material}
      />
      <mesh
        geometry={nodes.mesh_100.geometry}
        material={nodes.mesh_100.material}
      />
      <mesh
        geometry={nodes.mesh_101.geometry}
        material={nodes.mesh_101.material}
      />
      <mesh
        geometry={nodes.mesh_102.geometry}
        material={nodes.mesh_102.material}
      />
      <mesh
        geometry={nodes.mesh_103.geometry}
        material={nodes.mesh_103.material}
      />
      <mesh
        geometry={nodes.mesh_104.geometry}
        material={nodes.mesh_104.material}
      />
      <mesh
        geometry={nodes.mesh_105.geometry}
        material={nodes.mesh_105.material}
      />
      <mesh
        geometry={nodes.mesh_106.geometry}
        material={nodes.mesh_106.material}
      />
      <mesh
        geometry={nodes.mesh_107.geometry}
        material={nodes.mesh_107.material}
      />
      <mesh
        geometry={nodes.mesh_108.geometry}
        material={nodes.mesh_108.material}
      />
      <mesh
        geometry={nodes.mesh_109.geometry}
        material={nodes.mesh_109.material}
      />
      <mesh
        geometry={nodes.mesh_110.geometry}
        material={nodes.mesh_110.material}
      />
      <mesh
        geometry={nodes.mesh_111.geometry}
        material={nodes.mesh_111.material}
      />
      <mesh
        geometry={nodes.mesh_112.geometry}
        material={nodes.mesh_112.material}
      />
      <mesh
        geometry={nodes.mesh_113.geometry}
        material={nodes.mesh_113.material}
      />
      <mesh
        geometry={nodes.mesh_114.geometry}
        material={nodes.mesh_114.material}
      />
      <mesh
        geometry={nodes.mesh_115.geometry}
        material={nodes.mesh_115.material}
      />
      <mesh
        geometry={nodes.mesh_116.geometry}
        material={nodes.mesh_116.material}
      />
      <mesh
        geometry={nodes.mesh_117.geometry}
        material={nodes.mesh_117.material}
      />
      <mesh
        geometry={nodes.mesh_118.geometry}
        material={nodes.mesh_118.material}
      />
      <mesh
        geometry={nodes.mesh_119.geometry}
        material={nodes.mesh_119.material}
      />
      <mesh
        geometry={nodes.mesh_120.geometry}
        material={nodes.mesh_120.material}
      />
      <mesh
        geometry={nodes.mesh_121.geometry}
        material={nodes.mesh_121.material}
      />
      <mesh
        geometry={nodes.mesh_122.geometry}
        material={nodes.mesh_122.material}
      />
      <mesh
        geometry={nodes.mesh_123.geometry}
        material={nodes.mesh_123.material}
      />
      <mesh
        geometry={nodes.mesh_124.geometry}
        material={nodes.mesh_124.material}
      />
      <mesh
        geometry={nodes.mesh_125.geometry}
        material={nodes.mesh_125.material}
      />
      <mesh
        geometry={nodes.mesh_126.geometry}
        material={nodes.mesh_126.material}
      />
      <mesh
        geometry={nodes.mesh_127.geometry}
        material={nodes.mesh_127.material}
      />
      <mesh
        geometry={nodes.mesh_128.geometry}
        material={nodes.mesh_128.material}
      />
      <mesh
        geometry={nodes.mesh_129.geometry}
        material={nodes.mesh_129.material}
      />
      <mesh
        geometry={nodes.mesh_130.geometry}
        material={nodes.mesh_130.material}
      />
      <mesh
        geometry={nodes.mesh_131.geometry}
        material={nodes.mesh_131.material}
      />
      <mesh
        geometry={nodes.mesh_132.geometry}
        material={nodes.mesh_132.material}
      />
      <mesh
        geometry={nodes.mesh_133.geometry}
        material={nodes.mesh_133.material}
      />
      <mesh
        geometry={nodes.mesh_134.geometry}
        material={nodes.mesh_134.material}
      />
      <mesh
        geometry={nodes.mesh_135.geometry}
        material={nodes.mesh_135.material}
      />
      <mesh
        geometry={nodes.mesh_136.geometry}
        material={nodes.mesh_136.material}
      />
      <mesh
        geometry={nodes.mesh_137.geometry}
        material={nodes.mesh_137.material}
      />
      <mesh
        geometry={nodes.mesh_138.geometry}
        material={nodes.mesh_138.material}
      />
      <mesh
        geometry={nodes.mesh_139.geometry}
        material={nodes.mesh_139.material}
      />
      <mesh
        geometry={nodes.mesh_140.geometry}
        material={nodes.mesh_140.material}
      />
      <mesh
        geometry={nodes.mesh_141.geometry}
        material={nodes.mesh_141.material}
      />
      <mesh
        geometry={nodes.mesh_142.geometry}
        material={nodes.mesh_142.material}
      />
      <mesh
        geometry={nodes.mesh_143.geometry}
        material={nodes.mesh_143.material}
      />
      <mesh
        geometry={nodes.mesh_144.geometry}
        material={nodes.mesh_144.material}
      />
      <mesh
        geometry={nodes.mesh_145.geometry}
        material={nodes.mesh_145.material}
      />
      <mesh
        geometry={nodes.mesh_146.geometry}
        material={nodes.mesh_146.material}
      />
      <mesh
        geometry={nodes.mesh_147.geometry}
        material={nodes.mesh_147.material}
      />
      <mesh
        geometry={nodes.mesh_148.geometry}
        material={nodes.mesh_148.material}
      />
      <mesh
        geometry={nodes.mesh_149.geometry}
        material={nodes.mesh_149.material}
      />
      <mesh
        geometry={nodes.mesh_150.geometry}
        material={nodes.mesh_150.material}
      />
      <mesh
        geometry={nodes.mesh_151.geometry}
        material={nodes.mesh_151.material}
      />
      <mesh
        geometry={nodes.mesh_152.geometry}
        material={nodes.mesh_152.material}
      />
      <mesh
        geometry={nodes.mesh_153.geometry}
        material={nodes.mesh_153.material}
      />
      <mesh
        geometry={nodes.mesh_154.geometry}
        material={nodes.mesh_154.material}
      />
      <mesh
        geometry={nodes.mesh_155.geometry}
        material={nodes.mesh_155.material}
      />
      <mesh
        geometry={nodes.mesh_156.geometry}
        material={nodes.mesh_156.material}
      />
      <mesh
        geometry={nodes.mesh_157.geometry}
        material={nodes.mesh_157.material}
      />
      <mesh
        geometry={nodes.mesh_158.geometry}
        material={nodes.mesh_158.material}
      />
      <mesh
        geometry={nodes.mesh_159.geometry}
        material={nodes.mesh_159.material}
      />
      <mesh
        geometry={nodes.mesh_160.geometry}
        material={nodes.mesh_160.material}
      />
      <mesh
        geometry={nodes.mesh_161.geometry}
        material={nodes.mesh_161.material}
      />
      <mesh
        geometry={nodes.mesh_162.geometry}
        material={nodes.mesh_162.material}
      />
      <mesh
        geometry={nodes.mesh_163.geometry}
        material={nodes.mesh_163.material}
      />
      <mesh
        geometry={nodes.mesh_164.geometry}
        material={nodes.mesh_164.material}
      />
      <mesh
        geometry={nodes.mesh_165.geometry}
        material={nodes.mesh_165.material}
      />
      <mesh
        geometry={nodes.mesh_166.geometry}
        material={nodes.mesh_166.material}
      />
      <mesh
        geometry={nodes.mesh_167.geometry}
        material={nodes.mesh_167.material}
      />
      <mesh
        geometry={nodes.mesh_168.geometry}
        material={nodes.mesh_168.material}
      />
      <mesh
        geometry={nodes.mesh_169.geometry}
        material={nodes.mesh_169.material}
      />
      <mesh
        geometry={nodes.mesh_170.geometry}
        material={nodes.mesh_170.material}
      />
      <mesh
        geometry={nodes.mesh_171.geometry}
        material={nodes.mesh_171.material}
      />
      <mesh
        geometry={nodes.mesh_172.geometry}
        material={nodes.mesh_172.material}
      />
      <mesh
        geometry={nodes.mesh_173.geometry}
        material={nodes.mesh_173.material}
      />
      <mesh
        geometry={nodes.mesh_174.geometry}
        material={nodes.mesh_174.material}
      />
      <mesh
        geometry={nodes.mesh_175.geometry}
        material={nodes.mesh_175.material}
      />
      <mesh
        geometry={nodes.mesh_176.geometry}
        material={nodes.mesh_176.material}
      />
      <mesh
        geometry={nodes.mesh_177.geometry}
        material={nodes.mesh_177.material}
      />
      <mesh
        geometry={nodes.mesh_178.geometry}
        material={nodes.mesh_178.material}
      />
      <mesh
        geometry={nodes.mesh_179.geometry}
        material={nodes.mesh_179.material}
      />
      <mesh
        geometry={nodes.mesh_180.geometry}
        material={nodes.mesh_180.material}
      />
      <mesh
        geometry={nodes.mesh_181.geometry}
        material={nodes.mesh_181.material}
      />
      <mesh
        geometry={nodes.mesh_182.geometry}
        material={nodes.mesh_182.material}
      />
      <mesh
        geometry={nodes.mesh_183.geometry}
        material={nodes.mesh_183.material}
      />
      <mesh
        geometry={nodes.mesh_184.geometry}
        material={nodes.mesh_184.material}
      />
      <mesh
        geometry={nodes.mesh_185.geometry}
        material={nodes.mesh_185.material}
      />
      <mesh
        geometry={nodes.mesh_186.geometry}
        material={nodes.mesh_186.material}
      />
      <mesh
        geometry={nodes.mesh_187.geometry}
        material={nodes.mesh_187.material}
      />
      <mesh
        geometry={nodes.mesh_188.geometry}
        material={nodes.mesh_188.material}
      />
      <mesh
        geometry={nodes.mesh_189.geometry}
        material={nodes.mesh_189.material}
      />
      <mesh
        geometry={nodes.mesh_190.geometry}
        material={nodes.mesh_190.material}
      />
      <mesh
        geometry={nodes.mesh_191.geometry}
        material={nodes.mesh_191.material}
      />
      <mesh
        geometry={nodes.mesh_192.geometry}
        material={nodes.mesh_192.material}
      />
      <mesh
        geometry={nodes.mesh_193.geometry}
        material={nodes.mesh_193.material}
      />
      <mesh
        geometry={nodes.mesh_194.geometry}
        material={nodes.mesh_194.material}
      />
      <mesh
        geometry={nodes.mesh_195.geometry}
        material={nodes.mesh_195.material}
      />
      <mesh
        geometry={nodes.mesh_196.geometry}
        material={nodes.mesh_196.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_197.geometry}
        material={nodes.mesh_197.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_198.geometry}
        material={nodes.mesh_198.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_199.geometry}
        material={nodes.mesh_199.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_200.geometry}
        material={nodes.mesh_200.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_201.geometry}
        material={nodes.mesh_201.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_202.geometry}
        material={nodes.mesh_202.material}
      />
      <mesh
        geometry={nodes.mesh_203.geometry}
        material={nodes.mesh_203.material}
      />
      <mesh
        geometry={nodes.mesh_204.geometry}
        material={nodes.mesh_204.material}
      />
      <mesh
        geometry={nodes.mesh_205.geometry}
        material={nodes.mesh_205.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_206.geometry}
        material={nodes.mesh_206.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_207.geometry}
        material={nodes.mesh_207.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_208.geometry}
        material={nodes.mesh_208.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_209.geometry}
        material={nodes.mesh_209.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_210.geometry}
        material={nodes.mesh_210.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_211.geometry}
        material={nodes.mesh_211.material}
      />
      <mesh
        geometry={nodes.mesh_212.geometry}
        material={nodes.mesh_212.material}
      />
      <mesh
        geometry={nodes.mesh_213.geometry}
        material={nodes.mesh_213.material}
      />
      <mesh
        geometry={nodes.mesh_214.geometry}
        material={nodes.mesh_214.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_215.geometry}
        material={nodes.mesh_215.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_216.geometry}
        material={nodes.mesh_216.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_217.geometry}
        material={nodes.mesh_217.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_218.geometry}
        material={nodes.mesh_218.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_219.geometry}
        material={nodes.mesh_219.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_220.geometry}
        material={nodes.mesh_220.material}
      />
      <mesh
        geometry={nodes.mesh_221.geometry}
        material={nodes.mesh_221.material}
      />
      <mesh
        geometry={nodes.mesh_222.geometry}
        material={nodes.mesh_222.material}
      />
      <mesh
        geometry={nodes.mesh_223.geometry}
        material={nodes.mesh_223.material}
      />
      <mesh
        geometry={nodes.mesh_224.geometry}
        material={nodes.mesh_224.material}
      />
      <mesh
        geometry={nodes.mesh_225.geometry}
        material={nodes.mesh_225.material}
      />
      <mesh
        geometry={nodes.mesh_226.geometry}
        material={nodes.mesh_226.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_227.geometry}
        material={nodes.mesh_227.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_228.geometry}
        material={nodes.mesh_228.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_229.geometry}
        material={nodes.mesh_229.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_230.geometry}
        material={nodes.mesh_230.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_231.geometry}
        material={nodes.mesh_231.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_232.geometry}
        material={nodes.mesh_232.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_233.geometry}
        material={nodes.mesh_233.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_234.geometry}
        material={nodes.mesh_234.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_235.geometry}
        material={nodes.mesh_235.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_236.geometry}
        material={nodes.mesh_236.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_237.geometry}
        material={nodes.mesh_237.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_238.geometry}
        material={nodes.mesh_238.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_239.geometry}
        material={nodes.mesh_239.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_240.geometry}
        material={nodes.mesh_240.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_241.geometry}
        material={nodes.mesh_241.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_242.geometry}
        material={nodes.mesh_242.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_243.geometry}
        material={nodes.mesh_243.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_244.geometry}
        material={nodes.mesh_244.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_245.geometry}
        material={nodes.mesh_245.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_246.geometry}
        material={nodes.mesh_246.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_247.geometry}
        material={nodes.mesh_247.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_248.geometry}
        material={nodes.mesh_248.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_249.geometry}
        material={nodes.mesh_249.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_250.geometry}
        material={nodes.mesh_250.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_251.geometry}
        material={nodes.mesh_251.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_252.geometry}
        material={nodes.mesh_252.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_253.geometry}
        material={nodes.mesh_253.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_254.geometry}
        material={nodes.mesh_254.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_255.geometry}
        material={nodes.mesh_255.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_256.geometry}
        material={nodes.mesh_256.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_257.geometry}
        material={nodes.mesh_257.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_258.geometry}
        material={nodes.mesh_258.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_259.geometry}
        material={nodes.mesh_259.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_260.geometry}
        material={nodes.mesh_260.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_261.geometry}
        material={nodes.mesh_261.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_262.geometry}
        material={nodes.mesh_262.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_263.geometry}
        material={nodes.mesh_263.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_264.geometry}
        material={nodes.mesh_264.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_265.geometry}
        material={nodes.mesh_265.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_266.geometry}
        material={nodes.mesh_266.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_267.geometry}
        material={nodes.mesh_267.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_268.geometry}
        material={nodes.mesh_268.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_269.geometry}
        material={nodes.mesh_269.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_270.geometry}
        material={nodes.mesh_270.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_271.geometry}
        material={nodes.mesh_271.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_272.geometry}
        material={nodes.mesh_272.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_273.geometry}
        material={nodes.mesh_273.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_274.geometry}
        material={nodes.mesh_274.material}
      />
      <mesh
        geometry={nodes.mesh_275.geometry}
        material={nodes.mesh_275.material}
      />
      <mesh
        geometry={nodes.mesh_276.geometry}
        material={nodes.mesh_276.material}
      />
      <mesh
        geometry={nodes.mesh_277.geometry}
        material={nodes.mesh_277.material}
      />
      <mesh
        geometry={nodes.mesh_278.geometry}
        material={nodes.mesh_278.material}
      />
      <mesh
        geometry={nodes.mesh_279.geometry}
        material={nodes.mesh_279.material}
      />
      <mesh
        geometry={nodes.mesh_280.geometry}
        material={nodes.mesh_280.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_281.geometry}
        material={nodes.mesh_281.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_282.geometry}
        material={nodes.mesh_282.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_283.geometry}
        material={nodes.mesh_283.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_284.geometry}
        material={nodes.mesh_284.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_285.geometry}
        material={nodes.mesh_285.material}
        position={[-3.96, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_286.geometry}
        material={nodes.mesh_286.material}
      />
      <mesh
        geometry={nodes.mesh_287.geometry}
        material={nodes.mesh_287.material}
      />
      <mesh
        geometry={nodes.mesh_288.geometry}
        material={nodes.mesh_288.material}
      />
      <mesh
        geometry={nodes.mesh_289.geometry}
        material={nodes.mesh_289.material}
      />
      <mesh
        geometry={nodes.mesh_290.geometry}
        material={nodes.mesh_290.material}
      />
      <mesh
        geometry={nodes.mesh_291.geometry}
        material={nodes.mesh_291.material}
      />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <mesh
        geometry={nodes.mesh_292.geometry}
        material={nodes.mesh_292.material}
      />
    </group>
  );
}

useGLTF.preload('/lego_world-transformed.glb');
